import { TaskStatus, TaskPriority, UpdateTaskRequest } from '@/lib/backend';

export function createStatusUpdate(status: TaskStatus): UpdateTaskRequest {
  return {
    id: null,
    title: null,
    description: null,
    priority: null,
    status,
    vehicle_plate: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_make: null,
    vin: null,
    ppf_zones: null,
    custom_ppf_zones: null,
    client_id: null,
    customer_name: null,
    customer_email: null,
    customer_phone: null,
    customer_address: null,
    external_id: null,
    lot_film: null,
    checklist_completed: null,
    scheduled_date: null,
    start_time: null,
    end_time: null,
    date_rdv: null,
    heure_rdv: null,
    template_id: null,
    workflow_id: null,
    estimated_duration: null,
    notes: null,
    tags: null,
    technician_id: null,
  };
}

export function createPriorityUpdate(priority: TaskPriority): UpdateTaskRequest {
  return {
    id: null,
    title: null,
    description: null,
    priority,
    status: null,
    vehicle_plate: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_make: null,
    vin: null,
    ppf_zones: null,
    custom_ppf_zones: null,
    client_id: null,
    customer_name: null,
    customer_email: null,
    customer_phone: null,
    customer_address: null,
    external_id: null,
    lot_film: null,
    checklist_completed: null,
    scheduled_date: null,
    start_time: null,
    end_time: null,
    date_rdv: null,
    heure_rdv: null,
    template_id: null,
    workflow_id: null,
    estimated_duration: null,
    notes: null,
    tags: null,
    technician_id: null,
  };
}

export function createTechnicianUpdate(technician_id: string): UpdateTaskRequest {
  return {
    id: null,
    title: null,
    description: null,
    priority: null,
    status: null,
    vehicle_plate: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_make: null,
    vin: null,
    ppf_zones: null,
    custom_ppf_zones: null,
    client_id: null,
    customer_name: null,
    customer_email: null,
    customer_phone: null,
    customer_address: null,
    external_id: null,
    lot_film: null,
    checklist_completed: null,
    scheduled_date: null,
    start_time: null,
    end_time: null,
    date_rdv: null,
    heure_rdv: null,
    template_id: null,
    workflow_id: null,
    estimated_duration: null,
    notes: null,
    tags: null,
    technician_id,
  };
}

export function createNotesUpdate(notes: string): UpdateTaskRequest {
  return {
    id: null,
    title: null,
    description: null,
    priority: null,
    status: null,
    vehicle_plate: null,
    vehicle_model: null,
    vehicle_year: null,
    vehicle_make: null,
    vin: null,
    ppf_zones: null,
    custom_ppf_zones: null,
    client_id: null,
    customer_name: null,
    customer_email: null,
    customer_phone: null,
    customer_address: null,
    external_id: null,
    lot_film: null,
    checklist_completed: null,
    scheduled_date: null,
    start_time: null,
    end_time: null,
    date_rdv: null,
    heure_rdv: null,
    template_id: null,
    workflow_id: null,
    estimated_duration: null,
    notes,
    tags: null,
    technician_id: null,
  };
}
