// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

// Reports types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportCapabilities = { version: string, status: string, available_exports: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual intervention report result payload returned to frontend export flows.
 */
export type InterventionReportResult = { success: boolean, download_url: string | null, file_path: string | null, file_name: string | null, format: string, file_size: bigint | null, generated_at: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Completion time prediction result contract shared across reporting/analytics.
 */
export type CompletionTimePrediction = { predicted_duration_minutes: number, confidence_interval: [number, number], factors_influencing: Array<string>, historical_average: number, prediction_accuracy: number, };
