// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single checklist item belonging to a task.
 */
export type ChecklistItem = { id: string, task_id: string, description: string, position: number, is_completed: boolean, completed_at: string | null, completed_by: string | null, notes: string | null, created_at: string, updated_at: string, };
