// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request DTO for creating a user.
 */
export type CreateUserRequest = { email: string, first_name: string, last_name: string, role: string, password: string, };
