// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentType } from "./AttachmentType";

/**
 * Create quote attachment request
 */
export type CreateQuoteAttachmentRequest = { file_name: string, file_path: string, file_size: bigint, mime_type: string, attachment_type: AttachmentType | null, description: string | null, };
