// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuoteItemKind } from "./QuoteItemKind";

/**
 * Create quote item request
 */
export type CreateQuoteItemRequest = { kind: QuoteItemKind, label: string, description: string | null, qty: number, unit_price: bigint, tax_rate: number | null, material_id: string | null, position: number | null, };
