// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new checklist item for a task.
 */
export type CreateChecklistItemRequest = { task_id: string, description: string, position: number | null, };
