// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskFilter } from "./TaskFilter";

/**
 * Request for getting tasks with clients
 */
export type GetTasksWithClientsRequest = { filter: TaskFilter | null, page: number | null, limit: number | null, correlation_id: string | null, };
