// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskFilter } from "./TaskFilter";

/**
 * Request for getting task statistics
 */
export type GetTaskStatisticsRequest = { filter: TaskFilter | null, correlation_id: string | null, };
