// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateQuoteAttachmentRequest } from "./UpdateQuoteAttachmentRequest";

/**
 * TODO: document
 */
export type QuoteAttachmentUpdateRequest = { quote_id: string, attachment_id: string, data: UpdateQuoteAttachmentRequest, correlation_id: string | null, };
