// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuoteMonthlyCount } from "./QuoteMonthlyCount";

/**
 * Aggregate statistics for all quotes (not limited by pagination).
 */
export type QuoteStats = { total: bigint, draft: bigint, sent: bigint, accepted: bigint, rejected: bigint, expired: bigint, converted: bigint, 
/**
 * Monthly counts for the last 6 months: each entry is (year_month, count).
 */
monthly_counts: Array<QuoteMonthlyCount>, };
