// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateQuoteItemRequest } from "./CreateQuoteItemRequest";

/**
 * TODO: document
 */
export type QuoteItemAddRequest = { quote_id: string, item: CreateQuoteItemRequest, correlation_id: string | null, };
