// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateQuoteRequest } from "./CreateQuoteRequest";

/**
 * TODO: document
 */
export type QuoteCreateRequest = { data: CreateQuoteRequest, correlation_id: string | null, };
