// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TODO: document
 */
export type QuoteItemDeleteRequest = { quote_id: string, item_id: string, correlation_id: string | null, };
