// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateQuoteRequest } from "./UpdateQuoteRequest";

/**
 * TODO: document
 */
export type QuoteUpdateRequest = { id: string, data: UpdateQuoteRequest, correlation_id: string | null, };
