// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuoteQuery } from "./QuoteQuery";

/**
 * TODO: document
 */
export type QuoteListRequest = { filters: QuoteQuery, correlation_id: string | null, };
