// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreateQuoteAttachmentRequest } from "./CreateQuoteAttachmentRequest";

/**
 * TODO: document
 */
export type QuoteAttachmentCreateRequest = { quote_id: string, data: CreateQuoteAttachmentRequest, correlation_id: string | null, };
