// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdateQuoteItemRequest } from "./UpdateQuoteItemRequest";

/**
 * TODO: document
 */
export type QuoteItemUpdateRequest = { quote_id: string, item_id: string, data: UpdateQuoteItemRequest, correlation_id: string | null, };
