// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to convert an accepted quote into a task.
 *
 * The `vehicle_*` and `scheduled_date` fields provide the data
 * needed to create the corresponding task at the IPC orchestration
 * layer.
 */
export type QuoteConvertToTaskRequest = { quote_id: string, vehicle_plate: string, vehicle_model: string, vehicle_make: string | null, vehicle_year: string | null, vehicle_vin: string | null, scheduled_date: string | null, ppf_zones: Array<string> | null, correlation_id: string | null, };
