// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One month's quote count.
 */
export type QuoteMonthlyCount = { 
/**
 * e.g. "2026-03"
 */
month: string, count: bigint, };
