// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote status enumeration
 */
export type QuoteStatus = "draft" | "sent" | "accepted" | "rejected" | "expired" | "converted" | "changes_requested";
