// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote item kind enumeration
 */
export type QuoteItemKind = "labor" | "material" | "service" | "discount";
