// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter for task queries
 */
export type TaskFilter = { assigned_to: string | null, client_id: string | null, status: string | null, priority: string | null, region: string | null, include_completed: boolean | null, date_from: string | null, date_to: string | null, };
