// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update the completion state of a checklist item.
 */
export type UpdateChecklistItemRequest = { is_completed: boolean, notes: string | null, };
