// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QuoteItemKind } from "./QuoteItemKind";

/**
 * Update quote item request
 */
export type UpdateQuoteItemRequest = { kind: QuoteItemKind | null, label: string | null, description: string | null, qty: number | null, unit_price: bigint | null, tax_rate: number | null, material_id: string | null, position: number | null, };
