// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request DTO for updating a user.
 */
export type UpdateUserRequest = { email: string | null, first_name: string | null, last_name: string | null, role: string | null, is_active: boolean | null, };
