// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserAction } from "./UserAction";

/**
 * User request structure
 */
export type UserCrudRequest = { action: UserAction, };
